all:
  hosts:
    master-1:
      ansible_host: 158.160.60.13
      ip: 10.0.1.18
      access_ip: 10.0.1.18
      ansible_user: debian
    worker-1:
      ansible_host: 89.169.144.55
      ip: 10.0.1.31
      access_ip: 10.0.1.31
      ansible_user: debian
    worker-2:
      ansible_host: 51.250.70.224
      ip: 10.0.1.24
      access_ip: 10.0.1.24
      ansible_user: debian
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
